ZK-4634: Classic themes don't handle toolbar overflowPopup and align=…
zkoss/zk pull request #2123
Opened 2020-08-20 08:19 UTC by plijyfes

…"end"

2020-08-20 10:06 UTC, plijyfes commented on zul/src/archive/web/zul/less/_zkvariables.less
> +@toolbarHorizontalPadding:     16px;
compact

2020-08-20 10:22 UTC, plijyfes commented on zul/src/archive/web/js/zul/wgt/less/toolbar.less
> +				float: right;
remove float right

2020-08-20 10:35 UTC, scribetw requested changes
Iceblue compact, drop float: right

2020-08-21 06:25 UTC, scribetw commented
@zkadmin rebase

2020-08-21 06:26 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-08-21 06:29 UTC, merged