ZK-4546: Caching of EL method invocations
zkoss/zk pull request #2134
Opened 2020-08-26 07:59 UTC by DevChu

2020-08-28 02:58 UTC, plijyfes requested changes

2020-08-28 02:58 UTC, plijyfes commented on zel/src/org/zkoss/zel/BeanELResolver.java
> +		private int _hashCode;
move into constructor

2020-08-28 02:58 UTC, plijyfes commented on zel/src/org/zkoss/zel/BeanELResolver.java
> +			if (obj instanceof CachedMethodInfo) {
refactor

2020-08-28 02:58 UTC, plijyfes commented on zel/src/org/zkoss/zel/BeanELResolver.java
> +				clzMap = new ConcurrentHashMap<>();
check concurrent

2020-08-28 09:01 UTC, plijyfes approved these changes

2020-08-31 09:36 UTC, scribetw requested changes

2020-08-31 09:36 UTC, scribetw commented on zel/src/org/zkoss/zel/BeanELResolver.java
> +			Map<CachedMethodInfo, Method> clzMap = METHODS_CACHE.get(clazz);
Use other Lock other than synchorized

2020-09-02 09:11 UTC, plijyfes requested changes

2020-09-02 09:11 UTC, plijyfes commented on zel/src/org/zkoss/zel/impl/util/ReflectionUtil.java
> +    private static final int DEFAULT_CAPACITY = 16;
cacheSize getSystem

2020-09-02 09:11 UTC, plijyfes commented on zel/src/org/zkoss/zel/impl/util/ReflectionUtil.java
>  		classMap.put(propertyName, result);
one line

2020-09-02 09:11 UTC, plijyfes commented on zk/src/org/zkoss/zk/ui/util/ConventionWire.java
> +				return null;
null value is invalid

2020-09-03 09:48 UTC, scribetw approved these changes

2020-09-03 09:54 UTC, scribetw requested changes
In conventionWire, cache the "NotFound" result to prevent finding again

2020-09-03 10:15 UTC, scribetw commented on zk/src/org/zkoss/zk/ui/util/ConventionWire.java
> +				return NotFound.class.getFields()[0];
private static final Field EMPTY = NotFound.class.getFields()[0];

2020-09-03 10:35 UTC, scribetw approved these changes

2020-09-03 10:35 UTC, scribetw commented
@zkadmin rebase

2020-09-03 10:36 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-09-03 10:36 UTC, merged