ZK-4653: Provide a collection of constants for Keys and provide isPre…
zkoss/zk pull request #2151
Opened 2020-09-02 08:47 UTC by plijyfes

…ssed API

2020-09-02 09:34 UTC, plijyfes commented on zk/src/archive/web/js/zk/evt.js
> +					return false; // Keys combination is invalid
zk.error

2020-09-02 09:39 UTC, plijyfes commented on zk/src/archive/web/js/zk/evt.js
> +				switch (arg) {
if

2020-09-02 09:56 UTC, plijyfes commented on zk/src/archive/web/js/zk/keys.js
> + * Ref: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
Since 9.5.0

2020-09-02 10:05 UTC, scribetw requested changes
1. keys.js Javadoc
2. need some refine

2020-09-03 10:04 UTC, scribetw approved these changes

2020-09-03 10:22 UTC, scribetw commented
@zkadmin rebase

2020-09-03 10:24 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-09-03 10:25 UTC, merged