ZK-4664: Duplicate DOM id in Listbox with pagingPosition="both"
zkoss/zk pull request #2224
Opened 2020-10-16 09:11 UTC by DevChu

2020-10-16 10:05 UTC, scribetw requested changes
case

2020-10-20 09:11 UTC, plijyfes requested changes

2020-10-20 09:11 UTC, plijyfes commented on zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4664Test.java
> +		sendKeys(input, Keys.NUMPAD2);
'2'

2020-10-20 09:11 UTC, plijyfes commented on zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4664Test.java
> +		click(jq(".z-paging-button").eq(3));
comment

2020-10-20 09:45 UTC, plijyfes approved these changes

2020-10-21 07:49 UTC, scribetw approved these changes

2020-10-21 07:49 UTC, scribetw commented
@zkadmin rebase

2020-10-21 07:50 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-10-21 08:07 UTC, merged