ZK-4676: panel-touch incorrect height calculation
zkoss/zk pull request #2229
Opened 2020-10-20 08:58 UTC by DevChu

2020-10-20 09:49 UTC, scribetw requested changes
only add cave if iscroll is used

2020-10-20 10:01 UTC, plijyfes approved these changes

2020-10-20 10:34 UTC, scribetw approved these changes

2020-10-21 08:07 UTC, scribetw commented
@zkadmin rebase

2020-10-21 08:07 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-10-21 08:08 UTC, merged