ZK-4684: menuitem icon alignment
zkoss/zk pull request #2232
Opened 2020-10-21 10:06 UTC by plijyfes

2020-10-22 10:11 UTC, plijyfes commented on zktest/src/archive/test2/B95-ZK-4684.zul
> +				<menuitem iconSclass="z-icon-save" label="Save"/>
test img

2020-10-23 01:34 UTC, scribetw requested changes
test image + iconmSclass

2020-10-23 07:23 UTC, DevChu approved these changes

2020-10-23 07:28 UTC, scribetw approved these changes

2020-10-23 07:29 UTC, scribetw commented
@zkadmin rebase

2020-10-23 07:30 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-10-23 07:30 UTC, merged