ZK-4669: Incorrect size in horizontal splitter when resizing window b…
zkoss/zk pull request #2233
Opened 2020-10-22 09:59 UTC by DevChu

…y using css flex

2020-10-22 10:17 UTC, plijyfes commented on zul/src/org/zkoss/zul/Box.java
> +		setAttribute("org.zkoss.zul.css.flex", false);
TableLayout

2020-10-22 10:26 UTC, plijyfes requested changes
try to fix old flex

2020-10-23 07:22 UTC, plijyfes approved these changes

2020-10-23 07:28 UTC, scribetw approved these changes

2020-10-23 07:28 UTC, merged