[WIP] ZK-4068: datebox failing date format
zkoss/zk pull request #2241
Opened 2020-10-29 04:40 UTC by plijyfes

2020-10-29 10:43 UTC, scribetw requested changes
try using moment only to parse, even strictDate = false

2020-10-30 09:14 UTC, scribetw approved these changes

2020-10-30 09:32 UTC, scribetw commented
@zkadmin rebase

2020-10-30 09:33 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-10-30 09:45 UTC, merged