ZK-4644: Rendering Stepbar dynamically causes error
zkoss/zk pull request #2242
Opened 2020-10-29 09:32 UTC by DevChu

ZK-4645: Stepbar Error - render dynamically with model

2020-10-29 10:37 UTC, plijyfes requested changes

2020-10-29 10:37 UTC, plijyfes commented on zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4644Test.java
> +public class B95_ZK_4644Test extends WebDriverTestCase {
ZATS is enough

2020-10-29 10:42 UTC, scribetw approved these changes

2020-10-30 09:14 UTC, plijyfes approved these changes

2020-10-30 09:32 UTC, merged