ZK-4423: Kanban missing options to listen to portallayout onPortalMov…
zkoss/zk pull request #2247
Opened 2020-11-03 09:45 UTC by plijyfes

…e without affecting the UI

2020-11-04 09:54 UTC, plijyfes commented on zktest/src/archive/test2/config.properties
> +##zats##F95-ZK-4423.zul=A,E,Portallayout,onPortalMove,MVVM
add case for MVC

2020-11-04 10:11 UTC, scribetw requested changes
Add MVC usage zul case

2020-11-06 09:06 UTC, plijyfes commented on zktest/src/org/zkoss/zktest/test2/F95_ZK_4423Composer.java
> +	public void onPortalDrop3(PortalDropEvent evevt) {
typo and add portal move logic

2020-11-10 08:20 UTC, DevChu approved these changes

2020-11-10 08:45 UTC, scribetw approved these changes

2020-11-10 08:45 UTC, scribetw commented
@zkadmin rebase

2020-11-10 08:46 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-11-10 08:57 UTC, merged