ZK-4574: Clients.resize() doesn't work for hflex="min"
zkoss/zk pull request #2257
Opened 2020-11-13 07:52 UTC by DevChu

2020-11-16 10:14 UTC, plijyfes requested changes

2020-11-16 10:14 UTC, plijyfes commented on zk/src/archive/web/js/zk/widget.js
> +			if (this._cssflex)
testing min->number and number->number should clear or not

2020-11-17 09:34 UTC, scribetw requested changes

2020-11-17 09:34 UTC, scribetw commented on zktest/src/archive/test2/B95-ZK-4574.zul
> +		]]></attribute>
Add 1 to ""

2020-11-17 10:21 UTC, plijyfes approved these changes

2020-11-17 10:27 UTC, scribetw approved these changes

2020-11-17 10:27 UTC, scribetw commented
@zkadmin rebase

2020-11-17 10:28 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-11-17 10:38 UTC, merged