ZK-4719: tablet-ui disabled applies only partially
zkoss/zk pull request #2259
Opened 2020-11-16 09:52 UTC by plijyfes

2020-11-16 10:21 UTC, plijyfes commented on zk/src/org/zkoss/zk/ui/http/Wpds.java
> +		StringBuffer sb = new StringBuffer();
builder

2020-11-16 10:29 UTC, plijyfes commented on zk/src/archive/web/js/zk/zk.wpd
> +		var tabletSupported = zk.mobile && !zk.tabletUIDisabled;
zk.touchEnabled

2020-11-16 10:31 UTC, plijyfes commented on zktest/src/archive/test2/B95-ZK-4719.zul
> +	<label multiline="true">
add a button to reset the lib property after test

2020-11-16 10:49 UTC, scribetw requested changes
should refine

2020-11-17 09:35 UTC, scribetw approved these changes

2020-11-17 09:39 UTC, scribetw requested changes

2020-11-17 09:39 UTC, scribetw commented on zk/src/archive/web/js/zk/zk.wpd
>  	<script src="zk.js" jsdoc="true"/>
add macintel, tabletUIDisabled, and touchEnabled jsdoc

2020-11-17 10:08 UTC, DevChu approved these changes

2020-11-17 10:13 UTC, scribetw approved these changes

2020-11-17 10:19 UTC, scribetw commented
@zkadmin rebase

2020-11-17 10:20 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-11-17 10:26 UTC, merged