ZK-4729: z-errorbox disappears after clicking
zkoss/zk pull request #2307
Opened 2020-12-15 05:06 UTC by b952426

ZK-4729: z-errorbox disappears after clicking

2020-12-17 09:29 UTC, scribetw requested changes
check .gitignore
Need Test.java

2020-12-17 09:29 UTC, scribetw commented on zktest/debug/classes/test2/B95-ZK-4729.zul
> +		Purpose:
leave empty lines

2020-12-17 09:29 UTC, scribetw commented on zktest/debug/classes/test2/B95-ZK-4729.zul
> +			1. focus in the textbox and move out to trigger an error rbox appearing
move out to trigger => blur
error rbox => error box

2020-12-18 03:43 UTC, scribetw approved these changes

2020-12-18 03:59 UTC, plijyfes approved these changes

2020-12-18 04:00 UTC, plijyfes commented
@zkadmin rebase

2020-12-18 04:02 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-12-18 04:08 UTC, merged