ZK-4505: resize() doesn't reduce a groupbox height with title
zkoss/zk pull request #2310
Opened 2020-12-15 10:00 UTC by b952426

ZK-4505: resize() doesn't reduce a groupbox height with title

2020-12-17 09:34 UTC, scribetw requested changes

2020-12-17 09:34 UTC, scribetw commented on zktest/src/archive/test2/config.properties
> +##zats##B95-ZK-4505.zul=A,E, resize,vflex,min,grouopbox
,resize,

2020-12-17 09:34 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4505Test.java
> +		assertEquals(jq(".z-button").outerHeight(), jq(".z-groupbox-content").height());
jq(".z-button:eq(0)")
jq(".z-groupbox-content:eq(0)")

2020-12-18 03:41 UTC, plijyfes approved these changes

2020-12-18 06:23 UTC, DevChu approved these changes

2020-12-18 06:24 UTC, DevChu commented
@zkadmin rebase

2020-12-18 06:25 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-12-18 06:34 UTC, scribetw approved these changes

2020-12-18 06:34 UTC, merged