zk-4084: New added header is invisible when all headers have fixed width
zkoss/zk pull request #2323
Opened 2020-12-22 08:38 UTC by b952426

zk-4084: New added header is invisible when all headers have fixed width

2020-12-22 10:08 UTC, scribetw requested changes
Fix MeshWidget.js _fixHeaders

2020-12-23 09:45 UTC, scribetw requested changes

2020-12-23 09:45 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +				addHead = false,
shouldFix

2020-12-23 09:45 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +							addHead = true;
check !frozen && ehead.style.width first

2020-12-23 09:45 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +			if (addHead) {
return a || b

2020-12-24 09:57 UTC, scribetw requested changes

2020-12-24 09:57 UTC, scribetw commented on zktest/src/archive/test2/B95-ZK-4084.zul
> +		1. click the append button, should append the new listheader.
should see 3

2020-12-24 09:57 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4084Test.java
> +		Assert.assertEquals(jq(".z-listhead").width(), 400);
assertEquals(400, jq(".z-listhead").width());

2020-12-24 09:57 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +				shouldFix = false,
shouldCheckEmptyWidth = !this.frozen && this.eheadtbl && this.eheadtbl.style.width

2020-12-24 09:57 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +						if (!this.frozen && this.eheadtbl.style.width && w.getWidth() == undefined) {
if (shouldCheckEmptyWidth && w.getWidth())

2020-12-24 10:17 UTC, plijyfes approved these changes

2020-12-24 10:18 UTC, scribetw approved these changes

2020-12-24 10:19 UTC, scribetw commented
@zkadmin rebase

2020-12-24 10:20 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-12-24 10:47 UTC, scribetw requested changes

2020-12-24 10:47 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +				wd = _getMinWd(wgt) + (zk(wgt.ebody).hasVScroll() ? jq.scrollbarWidth() : 0) + bdw, // has to call _getMinWd first so wgt._minWd will be available
```suggestion
				wd = _getMinWd(wgt) + bdw, // has to call _getMinWd first so wgt._minWd will be available
```

2020-12-24 10:47 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +						if (shouldCheckEmptyWidth && w.getWidth()) {
shouldn't be nested

2020-12-24 10:47 UTC, scribetw commented on zktest/src/archive/test2/config.properties
> +##zats##B95-ZK-4084.zul=A,E,Width,AddChild
Need MeshWidget,HeadWidget at least

2020-12-25 02:56 UTC, scribetw approved these changes

2020-12-25 02:56 UTC, scribetw commented
@zkadmin rebase

2020-12-25 02:58 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2020-12-25 03:01 UTC, merged