ZK-4746: Selectbox component doesn't implement Disable interface
zkoss/zk pull request #2334
Opened 2020-12-29 01:42 UTC by b952426

ZK-4746: Selectbox component doesn't implement Disable interface

2020-12-29 09:07 UTC, scribetw requested changes

2020-12-29 09:07 UTC, scribetw commented on zul/src/org/zkoss/zul/Selectbox.java
> +public class Selectbox extends HtmlBasedComponent implements Disable {
Is there any component not implemented (Disable and Readonly)?

2020-12-29 09:07 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4746Test.java
> +public class B95_ZK_4746Test extends WebDriverTestCase {
Pure JUnit

Selectbox.class instaceof Disable

2020-12-30 01:58 UTC, plijyfes approved these changes

2020-12-30 02:00 UTC, DevChu approved these changes

2020-12-30 09:03 UTC, scribetw approved these changes

2020-12-30 09:43 UTC, merged