ZK-4742: client side http error handling not reachable
zkoss/zk pull request #2337
Opened 2020-12-30 08:50 UTC by b952426

ZK-4742: client side http error handling not reachable

2020-12-30 09:21 UTC, scribetw requested changes

2020-12-30 09:21 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4742Test.java
> +public class B95_ZK_4742Test extends WebDriverTestCase {
@ClassRule
	public static final ExternalZkXml CONFIG = new ExternalZkXml(B95_ZK_4742Test.class);

2020-12-30 10:00 UTC, cor3000 commented on zk/src/archive/web/js/zk/au.js
> +				var msg = reqInf.statusText;
this is an even more important fix, we should also have a test case for the default client side error handling, besides the custom error-uri config

2020-12-31 03:27 UTC, scribetw approved these changes

2020-12-31 03:27 UTC, plijyfes approved these changes

2021-01-05 10:45 UTC, scribetw commented
@zkadmin rebase

2021-01-05 10:46 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-01-05 10:47 UTC, merged