ZK-4619: The radiogroup of cloned radio is not updated
zkoss/zk pull request #2339
Opened 2021-01-04 01:42 UTC by b952426

ZK-4619: The radiogroup of cloned radio is not updated

2021-01-05 09:57 UTC, scribetw requested changes

2021-01-05 09:57 UTC, scribetw commented on zul/src/org/zkoss/zul/Radiogroup.java
> +			if(c instanceof Radio) {
if (

2021-01-05 09:57 UTC, scribetw commented on zul/src/org/zkoss/zul/Radiogroup.java
> +		getRadio(clone);
Fix Radio instead

2021-01-07 06:44 UTC, scribetw approved these changes

2021-01-07 06:46 UTC, plijyfes approved these changes

2021-01-07 06:46 UTC, plijyfes commented
@zkadmin rebase

2021-01-07 06:49 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-01-07 06:51 UTC, merged