refine ZK-3317: Listbox with hflex="min" produces a horizontal scrollbar
zkoss/zk pull request #2340
Opened 2021-01-05 02:50 UTC by b952426

refine ZK-3317: Listbox with hflex="min" produces a horizontal scrollbar

2021-01-07 04:01 UTC, scribetw requested changes

2021-01-08 09:53 UTC, scribetw requested changes

2021-01-08 09:53 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/MeshWidget.js
> +			this.$n().style.height = jq.px0(hgh + this.ehead.offsetHeight);
refine

2021-01-08 10:29 UTC, plijyfes approved these changes

2021-01-08 10:29 UTC, scribetw approved these changes

2021-01-08 10:33 UTC, DevChu approved these changes

2021-01-08 10:45 UTC, merged