refine ZK-4735
zkoss/zk pull request #2341
Opened 2021-01-05 06:45 UTC by DevChu

2021-01-05 10:16 UTC, scribetw requested changes

2021-01-05 10:16 UTC, scribetw commented on zk/src/org/zkoss/zk/ui/http/SimpleSession.java
> +		if (!getWebApp().getConfiguration().isTimerKeepAlive()) {
isTimerKeepAlive = true, session will not be invalidated

2021-01-05 10:18 UTC, scribetw requested changes
refine

2021-01-07 08:55 UTC, plijyfes approved these changes

2021-01-07 09:18 UTC, scribetw approved these changes

2021-01-07 09:18 UTC, merged