refine ZK-4759, flex min issue
zkoss/zk pull request #2351
Opened 2021-01-10 13:47 UTC by DevChu

2021-01-11 09:51 UTC, DevChu commented on zk/src/archive/web/js/zk/widget.js
>  				zWatch.listen({onSize: [wgt, zFlex.applyCSSFlex]});
delete flag cssFlexFixed

2021-01-11 09:54 UTC, DevChu commented on zk/src/archive/web/js/zk/widget.js
> +			if (cssFlexEnabled)
clear css flex flag

2021-01-12 04:30 UTC, scribetw approved these changes

2021-01-12 10:10 UTC, scribetw requested changes

2021-01-12 10:10 UTC, scribetw commented on zk/src/archive/web/js/zk/widget.js
> +					delete wgt._cssFlexFixed;
_cssFlexApplied

2021-01-12 11:01 UTC, scribetw approved these changes

2021-01-12 11:02 UTC, merged