ZK-4322: Listbox position is wrong after calling setSelectied in Safari
zkoss/zk pull request #2364
Opened 2021-01-15 10:33 UTC by b952426

ZK-4322: Listbox position is wrong after calling setSelectied in Safari

2021-01-15 11:00 UTC, scribetw requested changes
1. simplify case
2. remove the patch

2021-01-19 09:07 UTC, scribetw commented on zktest/src/archive/test2/B95-ZK-4322.zul
> +			model2.addToSelection(model2.getElementAt(model1.getSize()-1));
model2

2021-01-19 09:08 UTC, scribetw requested changes

2021-01-19 09:08 UTC, scribetw commented on zktest/src/archive/test2/B95-ZK-4322.zul
> +			model2.addToSelection(model2.getElementAt(model1.getSize()-1));
model2

2021-01-19 10:09 UTC, DevChu approved these changes

2021-01-19 10:09 UTC, scribetw approved these changes

2021-01-19 10:10 UTC, scribetw commented
@zkadmin rebase

2021-01-19 10:13 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-01-19 10:13 UTC, merged