ZK-4760: default error message box hard coded width (too small)
zkoss/zk pull request #2374
Opened 2021-01-21 08:51 UTC by b952426

ZK-4760: default error message box hard coded width (too small)

2021-01-21 09:58 UTC, b952426 commented on zul/src/archive/web/zul/less/_zkvariables.less
> +@messageboxViewportWidth:      477px;
remove 477

2021-01-21 09:59 UTC, b952426 commented on zul/src/archive/web/zul/less/profiles/_compact.less
> +@windowHeaderPadding: 3px 8px 5px;
use css

2021-01-21 10:00 UTC, b952426 commented on zul/src/archive/web/zul/less/profiles/_compact.less
> +@messageboxIconMarginLeft:16px;
@messageboxIconMarginLeft: 16px;

2021-01-21 10:00 UTC, b952426 commented on zul/src/archive/web/zul/less/profiles/_compact.less
> +@messageboxViewportWidth:357px;
remove

2021-01-21 10:13 UTC, scribetw requested changes

2021-01-22 07:12 UTC, b952426 commented on zul/src/archive/web/zul/less/_zkvariables.less
> +@messageboxWindowContentPadding:       20px 0px 16px;
@messageboxWindowContentPadding:  20px 0px 16px;

2021-01-22 07:16 UTC, b952426 commented on zul/src/archive/web/zul/less/_zkvariables.less
> +@messageboxSeparatorHeight:    16px;
viewport: margin-bottom:

2021-01-22 07:16 UTC, b952426 commented on zul/src/archive/web/zul/less/profiles/_compact.less
> +@messageboxSeparatorHeight: 12px;
remove

2021-01-22 07:58 UTC, DevChu approved these changes

2021-01-22 08:02 UTC, plijyfes approved these changes

2021-01-22 08:07 UTC, scribetw approved these changes

2021-01-22 10:13 UTC, scribetw commented
@zkadmin rebase

2021-01-22 10:16 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-01-22 10:16 UTC, merged