ZK-4762: listbox with frozen columns cannot show all headers under non-100% zoom level(non-smooth)
zkoss/zk pull request #2388
Opened 2021-01-27 04:43 UTC by b952426

ZK-4762: listbox with frozen columns cannot show all headers under non-100% zoom level(non-smooth)

2021-01-27 09:28 UTC, scribetw requested changes

2021-01-27 09:28 UTC, scribetw commented on zul/src/archive/web/js/zul/mesh/Frozen.js
> +					if (force || window.devicePixelRatio == 1 ? (wd <= 1) : (wd < 2)) {
just 2 is okay

2021-01-28 08:46 UTC, DevChu approved these changes

2021-01-28 08:47 UTC, scribetw approved these changes

2021-03-09 09:35 UTC, merged