[WIP]ZK-4330: provide select-all checkbox in tree component
zkoss/zk pull request #2399
Opened 2021-02-17 05:33 UTC by b952426

ZK-4330: provide select-all checkbox in tree component

2021-02-17 09:09 UTC, b952426 commented on zktest/src/archive/test2/F96-ZK-4330.zul
> +        <custom-attributes org.zkoss.zul.tree.initRodSize="-1"/>
put into tree3

2021-02-17 09:12 UTC, b952426 commented on zul/src/archive/web/js/zul/sel/Treecol.js
> +	_doClick: function (evt) {
doCmClick

2021-02-17 09:15 UTC, b952426 commented on zul/src/archive/web/js/zul/sel/Treecol.js
> +
delete
remove toServer? use important

2021-02-17 09:19 UTC, b952426 commented on zul/src/org/zkoss/zul/Tree.java
> +			CheckEvent evt = CheckEvent.getCheckEvent(request);
move to if

2021-02-17 09:20 UTC, b952426 commented on zul/src/org/zkoss/zul/Tree.java
> +		} else if (_model != null && cmd.equals("onCheckSelectRow")) {
_model instanceof Selectable

2021-02-17 09:35 UTC, b952426 commented on zul/src/archive/web/js/zul/sel/Treerow.js
> +			tree.fire('onCheckSelectRow', this.parent.isSelected(), {toServer: true});
onSelect

2021-02-17 09:46 UTC, b952426 commented on zul/src/archive/web/js/zul/sel/SelectWidget.js
> +			}
select widget: onUpdateSelectAll

2021-02-17 09:59 UTC, b952426 commented on zul/src/archive/web/js/zul/sel/SelectWidget.js
> +		for (var it = this.getBodyWidgetIterator({skipHidden: skipHidden}), w; (w = it.next());) {
other issue

2021-02-22 04:21 UTC, scribetw approved these changes
Open an issue about SelectElement

2021-02-22 04:21 UTC, scribetw commented on zul/src/org/zkoss/zul/Select.java
> +public abstract class Select extends MeshElement {
at this moment just open an issue

2021-02-22 04:21 UTC, scribetw commented on zul/src/archive/web/js/zul/sel/Treeitem.js
> +				tree._updHeaderCM();
if (open) {

}

2021-02-23 09:06 UTC, scribetw commented on zul/src/org/zkoss/zul/Tree.java
> +		} else if (cmd.equals("onUpdateSelectAll") && _model != null && _model instanceof Selectable) {
var b = _model instanceof Selectable

2021-02-23 09:07 UTC, scribetw requested changes
extract condition

2021-02-25 09:06 UTC, b952426 commented on zul/src/archive/web/js/zul/sel/Treecol.js
> +	},
}

2021-03-12 03:49 UTC, plijyfes approved these changes

2021-03-12 08:01 UTC, scribetw approved these changes

2021-03-12 08:01 UTC, merged