ZK-4761: MVVM provide option to disable viewmodel annotation caches
zkoss/zk pull request #2401
Opened 2021-02-17 09:02 UTC by DevChu

2021-02-17 10:05 UTC, b952426 commented on zkbind/src/org/zkoss/bind/impl/BinderImpl.java
> -				methods = new HashMap<String, CachedItem<Method>>();
fake empty map

2021-02-22 04:41 UTC, scribetw requested changes

2021-02-22 04:41 UTC, scribetw commented on zcommon/src/org/zkoss/util/EmptyCacheMap.java
> +	private static final long serialVersionUID = 20210218L;
yymmddhhmmss

2021-02-22 04:41 UTC, scribetw commented on zcommon/src/org/zkoss/util/EmptyCacheMap.java
> +		return Collections.EMPTY_SET;
Coolections.emptySet()

2021-02-22 04:41 UTC, scribetw commented on zkbind/src/org/zkoss/bind/impl/BinderImpl.java
> +	private static final Map<Class<?>, List<Method>> _destroyMethodCache = DISABLE_METHOD_CACHE ? new EmptyCacheMap() : new CacheMap<Class<?>, List<Method>>(600,
Can be a singleton and use ConcurrentMap

2021-02-22 04:41 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4761Test.java
> +	private <T> T getField(Object obj, String fieldName) throws Exception {
move reflection to VM

2021-02-23 09:15 UTC, scribetw approved these changes

2021-02-23 09:15 UTC, scribetw commented on zcommon/src/org/zkoss/util/EmptyCacheMap.java
> + * @author jameschu
since

2021-03-11 06:44 UTC, plijyfes approved these changes

2021-03-11 07:32 UTC, merged