ZK-4524: blocking all user keyboard input during processing message showing
zkoss/zk pull request #2404
Opened 2021-02-19 09:07 UTC by b952426

ZK-4524: blocking all user keyboard input during processing message showing

2021-02-22 05:03 UTC, scribetw requested changes

2021-02-23 09:58 UTC, scribetw requested changes

2021-02-23 09:58 UTC, scribetw commented on zk/src/archive/web/js/zk/au.js
> +			jq(w).on('keydown', zk.$void);
Use two anchors around w, and send tab (or shift+tab) to the next focusable element

2021-02-23 09:58 UTC, scribetw commented on zk/src/archive/web/js/zk/au.js
> +		var w = uuid ? Widget.$(uuid) : null;
move to if

2021-02-23 09:58 UTC, scribetw commented on zk/src/archive/web/js/zk/utl.js
> +		jq('html').off('keydown', zk.$void);
consider moving to z_mask instead

2021-02-23 09:58 UTC, scribetw commented on zktest/src/archive/test2/F96-ZK-4524.zul
> +	<textbox></textbox>
`<textbox/>`

2021-02-23 09:58 UTC, scribetw commented on zktest/src/archive/test2/F96-ZK-4524.zul
> +	<button label="show busy" onClick='Clients.showBusy("processing");'/>
add a `<textbox />` here

2021-02-23 09:58 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4524Test.java
> +		actions.sendKeys(Keys.TAB, "browser showBusy", Keys.TAB, Keys.TAB, "browser showBusy").perform();
extract full mask case

2021-02-25 09:10 UTC, b952426 commented on zk/src/archive/web/js/zk/au.js
> +	disableKeydown: function (e) {
move to other suitable place

2021-02-25 09:19 UTC, b952426 commented on zk/src/archive/web/js/zk/au.js
> +		} else if (e.which == 9) { //tabKey
e.originalEvent.key==zKeys.TAB

2021-02-25 09:36 UTC, b952426 commented on zk/src/archive/web/js/zk/au.js
> +			jq(this).next(':input, [href], [tabindex]:not([tabindex="-1"])').focus();
jq(this).prevAll('button, [href], input, select, textarea,[tabindex]').filter(':not([tabindex="-1"])').first()

2021-02-26 09:52 UTC, b952426 commented on zk/src/archive/web/js/zk/au.js
> +		}
//if widget prev/next focusable element is null, focus last/first focusable element.
only tab. shifTab preventDefault

2021-03-12 08:13 UTC, scribetw approved these changes

2021-03-12 08:18 UTC, plijyfes approved these changes

2021-03-12 10:41 UTC, scribetw commented
@zkadmin rebase

2021-03-12 10:42 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-03-12 10:42 UTC, merged