ZK-4631: Add option to choose toolbar overflow icon
zkoss/zk pull request #2405
Opened 2021-02-23 08:13 UTC by b952426

ZK-4631: Add option to choose toolbar overflow icon

2021-02-25 09:57 UTC, b952426 commented on zul/src/archive/web/js/zul/wgt/Toolbar.js
> +		},
}

2021-02-25 10:00 UTC, b952426 commented on zul/src/archive/web/js/zul/wgt/mold/toolbar.js
> +				' class="', this.$s('overflowpopup-button'), ' ' + this.getOverflowPopupIconSclass(), ' z-icon-fw" aria-hidden="true"></i>');
,

2021-02-25 10:01 UTC, b952426 commented on zul/src/org/zkoss/zul/Toolbar.java
> +		render(renderer, "overflowPopupIconSclass", getOverflowPopupIconSclass());
if (!"start".equals(_align))
			render(renderer, "align", _align);

2021-03-10 08:46 UTC, scribetw requested changes

2021-03-10 08:46 UTC, scribetw commented on zul/src/archive/web/js/zul/wgt/Toolbar.js
> +				icon.className = (this.$s('overflowpopup-button') + ' ' + overflowPopupIconSclass + ' z-icon-fw');
`()` no need

2021-03-10 08:46 UTC, scribetw commented on zul/src/archive/web/js/zul/wgt/mold/toolbar.js
> +				' class="', this.$s('overflowpopup-button'), ' ', this.getOverflowPopupIconSclass(), ' z-icon-fw" aria-hidden="true"></i>');
_getIconXXX: function () {
   return this.$s('overflowpopup-button') + ' ' + overflowPopupIconSclass + ' z-icon-fw';
}

2021-03-10 08:46 UTC, scribetw commented on zul/src/org/zkoss/zul/Toolbar.java
> +	 * Returns the overflowPopupIconSclass name of this toolbar.
`@see overflowPopup`
Refine javadoc

2021-03-12 09:20 UTC, scribetw requested changes

2021-03-12 09:20 UTC, scribetw commented on zul/src/archive/web/js/zul/wgt/Toolbar.js
> +				icon.className = this._getOverflowpopupBtnClass();
OverflowPopup

2021-03-16 09:57 UTC, scribetw approved these changes

2021-03-16 09:58 UTC, plijyfes approved these changes

2021-03-16 10:49 UTC, scribetw commented
@zkadmin rebase

2021-03-16 10:51 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-03-16 10:52 UTC, merged