ZK-4597: Disabled Combobutton should not be able to focus or controlled by keyboard
zkoss/zk pull request #2411
Opened 2021-03-10 03:58 UTC by b952426

ZK-4597: Disabled Combobutton should not be able to focus or controlled by keyboard

2021-03-10 08:25 UTC, scribetw requested changes
If disabled, don't add tabindex (init and setproperty)

2021-03-10 08:25 UTC, scribetw commented on zktest/src/archive/test2/B96-ZK-4597.zul
> +</zk>
Add a case to toggle disable dynamically

2021-03-10 08:25 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4597Test.java
> +		Assert.assertFalse(jq("@textarea").exists());
isZKLogAvailable

2021-03-10 08:25 UTC, scribetw commented on zul/src/archive/web/js/zul/wgt/Combobutton.js
> +		if (this.isDisabled) {
isDisabled()

2021-03-12 09:40 UTC, scribetw requested changes

2021-03-12 09:40 UTC, scribetw commented on zul/src/archive/web/js/zul/wgt/Combobutton.js
> +				jq(n).attr('tabindex', v ? -1 : this._tabindex | 0);
`v ? null : ...`

2021-03-12 09:40 UTC, scribetw commented on zul/src/archive/web/js/zul/wgt/Combobutton.js
> +				jq(n).attr('disabled', v ? 'disabled' : null),
;

2021-03-12 09:40 UTC, scribetw commented on zul/src/archive/web/js/zul/wgt/mold/combobutton.js
> +	this._disabled ? out.push(' disabled="disabled" aria-disabled="true"') : out.push(' tabindex="', tabi, '"');
if ... else ...

2021-03-16 10:04 UTC, scribetw approved these changes

2021-03-16 10:05 UTC, plijyfes approved these changes

2021-03-16 10:52 UTC, scribetw commented
@zkadmin rebase

2021-03-16 10:52 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-03-16 10:53 UTC, merged