ZK-4808: menu click listener ignored (unexpectedly)
zkoss/zk pull request #2414
Opened 2021-03-11 07:35 UTC by b952426

ZK-4808: menu click listener ignored (unexpectedly)

2021-03-12 10:13 UTC, scribetw requested changes

2021-03-12 10:13 UTC, scribetw commented on zul/src/archive/web/js/zul/menu/less/menu.less
> +		top: 0;
add `right: 0;`

2021-03-12 10:13 UTC, scribetw commented on zul/src/archive/web/js/zul/menu/less/menu.less
> +		width: @menuIconSize + 10px;
use .z-menu-separator right and extract to a variable

2021-03-16 10:14 UTC, scribetw approved these changes

2021-03-16 10:15 UTC, plijyfes approved these changes

2021-03-16 10:54 UTC, scribetw commented
@zkadmin rebase

2021-03-16 10:54 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-03-16 10:56 UTC, merged