ZK-1209: Proxying ViewModel breaks binder annotations
zkoss/zk pull request #2417
Opened 2021-03-12 03:20 UTC by DevChu

2021-03-16 10:26 UTC, scribetw requested changes
1. Try immigrating AnnotationUtil to find annotations in proxy classes
2. Add a default Handler in zk

2021-03-25 03:05 UTC, scribetw approved these changes

2021-03-25 04:43 UTC, plijyfes approved these changes

2021-03-25 07:12 UTC, scribetw approved these changes

2021-03-25 07:12 UTC, scribetw commented
@zkadmin rebase

2021-03-25 07:15 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-03-25 07:18 UTC, merged