ZK-4783: Modify error message box CSS design (provide scrollbar while word-break fail)
zkoss/zk pull request #2418
Opened 2021-03-12 07:17 UTC by b952426

ZK-4783: Modify error message box CSS design (provide scrollbar while word-break fail)

2021-03-16 10:57 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4783Test.java
> +public class F96_ZK_4783Test extends WebDriverTestCase {
1. extract test method
2. comma space

2021-03-16 10:57 UTC, scribetw commented on zktest/src/archive/test2/F96-ZK-4783.zul
> +		<a id="breeze" href="?zktheme=breeze" label="Breeze" />
use template

2021-03-17 06:14 UTC, plijyfes approved these changes

2021-03-18 07:33 UTC, DevChu approved these changes

2021-03-18 07:35 UTC, scribetw requested changes

2021-03-18 07:35 UTC, scribetw commented on zktest/src/archive/test2/F96-ZK-4783.zul
> +		3. messagebox 3 width shoud be 600px.
?

2021-03-18 10:16 UTC, scribetw approved these changes

2021-03-18 10:16 UTC, scribetw commented
@zkadmin rebase

2021-03-18 10:18 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-03-18 10:25 UTC, merged