ZK-4600: readonly spinner buttons should not be clickable
zkoss/zk pull request #2426
Opened 2021-03-16 08:41 UTC by b952426

ZK-4600: readonly spinner buttons should not be clickable

2021-03-17 03:39 UTC, scribetw requested changes

2021-03-17 03:39 UTC, scribetw commented on zktest/src/archive/test2/B96-ZK-4600.zul
> +    <div>disabled</div>
can be removed

2021-03-17 03:39 UTC, scribetw commented on zul/src/archive/web/js/zul/inp/less/combo.less
> +			border-color: @inputBackgroundColor !important;
avoid important
Ask the designer about the readonly style

2021-03-18 07:56 UTC, scribetw requested changes
don't modify zklessChecker
other themes

2021-03-18 07:56 UTC, scribetw commented on zul/src/archive/web/js/zul/inp/less/combo.less
> +					border-color: @inputBorderColor;
readonly only

2021-03-18 07:56 UTC, scribetw commented on zul/src/archive/web/js/zul/inp/less/combo.less
> +					& + .z-spinner-button, & + .z-doublespinner-button {
Avoid using `:hover + .xxx` (see ZK-4153)

2021-03-18 07:56 UTC, scribetw commented on zul/src/archive/web/js/zul/inp/less/combo.less
> +	&:not(&-readonly):hover > i {
```
&-readonly:hover > i {
    display: none;
}
```

2021-03-19 10:23 UTC, DevChu requested changes

2021-03-19 10:23 UTC, DevChu commented on zul/src/archive/web/js/zul/inp/InputWidget.js
> +		if (this._readonly) jq(this.getInputNode()).removeClass(this.$s('readonly-focus'));
remove if
this.$s('focus')

2021-03-19 10:23 UTC, DevChu commented on zul/src/archive/web/js/zul/inp/less/combo.less
> +		&-input&-readonly-focus, &-input&-readonly-focus + &-button {
```
&-readonly .z-xxx-focus {
}
```

2021-03-23 08:51 UTC, closed without merging