refine ZK-4791 (test detach parent then child, which means detach the…
zkoss/zk pull request #2431
Opened 2021-03-18 01:51 UTC by DevChu

… detached component)

2021-03-18 08:22 UTC, scribetw requested changes
wait for 4778

2021-03-19 09:05 UTC, DevChu commented on zkbind/src/org/zkoss/bind/tracker/impl/BindUiLifeCycle.java
> +		BindComposer.storeVmIdBinderRelation(comp);
move to util

2021-03-19 09:09 UTC, DevChu commented on zkbind/src/org/zkoss/bind/impl/BinderImpl.java
> +			Matcher matcher = Pattern.compile("\\$([^.]*)\\..*$").matcher(command);
move to private Pattern
"\\$([^.]+)\\..*"

2021-03-19 09:11 UTC, DevChu commented on zkbind/src/org/zkoss/bind/BindComposer.java
> +		Desktop desktop = comp.getDesktop();
null safe

2021-03-25 03:09 UTC, scribetw approved these changes

2021-03-25 03:09 UTC, scribetw commented on zkbind/src/org/zkoss/bind/impl/BinderImpl.java
> +	private Pattern _callOtherVMCommandPattern = Pattern.compile("\\$([^.]*)\\..*$");
static final

2021-03-25 04:43 UTC, plijyfes approved these changes

2021-03-25 07:11 UTC, scribetw approved these changes

2021-03-25 07:11 UTC, merged