ZK-4763: Radiogroup selectedIndex error after radio moved
zkoss/zk pull request #2436
Opened 2021-03-18 07:34 UTC by plijyfes

2021-03-19 09:29 UTC, DevChu commented on zktest/src/archive/test2/config.properties
> +##zats##B95-ZK-4763.zul=A,E,Radio,Radiogroup
96

2021-03-19 09:32 UTC, DevChu requested changes

2021-03-19 09:32 UTC, DevChu commented on zktest/src/archive/test2/config.properties
> +##zats##B95-ZK-4763.zul=A,E,Radio,Radiogroup
96

2021-03-19 09:32 UTC, DevChu commented on zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4763Test.java
> +public class B96_ZK_4763Test extends WebDriverTestCase {
ZATSCase

2021-03-23 08:54 UTC, scribetw approved these changes

2021-03-23 08:54 UTC, DevChu approved these changes

2021-03-23 09:44 UTC, scribetw commented
@zkadmin rebase

2021-03-23 09:45 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-03-23 09:46 UTC, merged