refine ZK-4330 nested tree item checkmark disappears automatically
zkoss/zk pull request #2443
Opened 2021-03-23 02:51 UTC by b952426

refine ZK-4330 nested tree item checkmark disappears automatically

2021-03-23 03:03 UTC, scribetw approved these changes

2021-03-23 09:53 UTC, scribetw requested changes
Find out why onSelect(item) becomes chgSel ""

2021-03-26 03:20 UTC, scribetw approved these changes

2021-03-26 03:31 UTC, plijyfes approved these changes

2021-03-26 03:40 UTC, scribetw approved these changes

2021-03-26 03:57 UTC, merged