ZK-4595: support a way to re-sort a ListModel under MVVM pattern
zkoss/zk pull request #2459
Opened 2021-03-30 08:58 UTC by DevChu

2021-03-30 09:43 UTC, DevChu reviewed
extract to  interface Sortable<T> 
default void sort() {};

2021-03-30 10:45 UTC, scribetw requested changes
sort

2021-03-31 09:07 UTC, scribetw reviewed
Add tests

2021-04-01 09:18 UTC, scribetw requested changes

2021-04-01 09:18 UTC, scribetw commented on zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4595Test.java
> +		click(jq("$header5"));
add header4 but comment out

2021-04-01 10:41 UTC, scribetw approved these changes

2021-04-01 10:42 UTC, merged