ZK-4828: remove externally loaded resources with internal refs.
zkoss/zk pull request #2461
Opened 2021-03-31 03:24 UTC by b952426

ZK-4828: remove externally loaded resources with internal refs.

2021-03-31 09:16 UTC, scribetw requested changes

2021-03-31 09:16 UTC, scribetw commented on zk/src/archive/web/WEB-INF/tld/zk/core.dsp.tld
> +	Deprecated sicne 9.6.0
since

2021-03-31 09:16 UTC, scribetw commented on zk/src/org/zkoss/zk/fn/ZkFns.java
>  	public static boolean isEditionValid() {
`@Deprecated`

2021-03-31 09:16 UTC, scribetw commented on zkdoc/release-note
> +  + Deprecated the method of isEditionValid() and encodeWithZK() of org.zkoss.zk.fn.ZkFns.
and in DSP

2021-03-31 10:25 UTC, plijyfes approved these changes

2021-04-01 04:44 UTC, scribetw approved these changes

2021-04-01 04:44 UTC, scribetw commented
@zkadmin rebase

2021-04-01 04:44 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-04-01 04:47 UTC, merged