[WIP] convert js to ts
zkoss/zk pull request #2466
Opened 2021-04-01 08:21 UTC by plijyfes

2021-04-01 10:16 UTC, scribetw requested changes

2021-04-01 10:16 UTC, scribetw commented on zk/src/archive/web/js/zk/pkg.ts
> +		_afterLoads: {(): void}[] = [],
try (() => void)[]

2021-04-01 10:16 UTC, scribetw commented on zk/src/archive/web/js/zk/zuml/Parser.ts
> +	function _aftCreate(wgt, cwgts, node, opts): zk.Widget | zk.Widget[] | void {
return null | zk.Widget | zk.Widget[]

2021-04-06 09:35 UTC, plijyfes commented on zk/src/archive/web/js/zk/zuml/Parser.ts
> +	function _create(parent, e, args, cwgts): void | null {
return void only

2021-04-06 09:47 UTC, plijyfes reviewed
add es2015.promise to tsconfig

2021-04-06 10:02 UTC, DevChu approved these changes

2021-04-06 10:44 UTC, scribetw approved these changes

2021-04-06 10:44 UTC, merged