convert several js files to ts
zkoss/zk pull request #2468
Opened 2021-04-07 08:29 UTC by DevChu

2021-04-08 10:10 UTC, scribetw requested changes
numfmt viewed, start from gapi

2021-04-08 10:10 UTC, scribetw commented on zk/src/archive/web/js/zk/fmt/numfmt.ts
> -			base = '5';
'5'.toCharCode() ?

2021-04-09 09:21 UTC, scribetw requested changes

2021-04-09 09:21 UTC, scribetw commented on zk/src/archive/web/js/zk/mount.ts
> +					zkdt(zk.cut(props, 'dt').toString(), zk.cut(props, 'cu').toString(), zk.cut(props, 'uu').toString()
check undefined

2021-04-09 09:21 UTC, scribetw commented on zk/src/archive/web/js/zk/mount.ts
>  })(window);
remove window

2021-04-09 09:21 UTC, scribetw commented on zk/src/archive/web/js/zk/mount.ts
> +		return !(zk.ie && zk.ie < 11) || evt['returnValue'];
evt: Event

2021-04-09 09:21 UTC, scribetw commented on zk/src/archive/web/js/zk/widget.ts
> +		return [ofs[0] ? x - ofs[0] : x, ofs[1] ? y - ofs[1] : y];
no change

2021-04-11 02:37 UTC, DevChu commented on zk/src/archive/web/js/zk/mount.ts
> +		return !(zk.ie && zk.ie < 11) || evt['returnValue'];
jqEvent no returnValue

2021-04-12 09:49 UTC, DevChu commented on @types/zk/zFlex.d.ts
> +		clearCSSFlex(wgt: zk.Widget, o: string, clearAllSiblings?: boolean): void;
FlexOrient

2021-04-12 09:49 UTC, DevChu commented on zk/src/archive/web/js/zk/js.ts
> +// @ts-nocheck
remove

2021-04-12 09:49 UTC, DevChu commented on zk/src/archive/web/js/zk/mount.ts
> +					clearInterval(_paci['i']);
interface add i: number | undefined

2021-04-12 09:49 UTC, DevChu commented on zk/src/archive/web/js/zk/mount.ts
> +					zkdt(dtid ? dtid.toString() : undefined, cu ? cu.toString() : undefined, uu ? uu.toString() : undefined,
zk.cut(props, 'dt') as string | undefined

2021-04-12 09:53 UTC, scribetw approved these changes

2021-04-13 01:37 UTC, plijyfes approved these changes

2021-04-13 01:55 UTC, merged