ZK-4777: signature can have a background image
zkoss/zk pull request #2485
Opened 2021-04-14 08:22 UTC by b952426

ZK-4777: signature can have a background image

2021-04-16 09:11 UTC, scribetw requested changes
use a free image instead

2021-04-16 09:11 UTC, scribetw commented on zktest/src/archive/test2/F96-ZK-4777.zul
> +			backgroundImage="/zktest/test2/img/F96-ZK-4777-frame.png" backgroundColor="null" penColor="white"/>
try mvc way to pass `null`

2021-04-19 09:02 UTC, scribetw approved these changes

2021-04-20 03:39 UTC, plijyfes approved these changes

2021-04-20 03:40 UTC, scribetw commented
@zkadmin rebase

2021-04-20 03:41 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-04-20 03:42 UTC, merged