refine ZK-4846
zkoss/zk pull request #2497
Opened 2021-04-21 01:58 UTC by DevChu

2021-04-21 09:06 UTC, scribetw requested changes

2021-04-21 09:06 UTC, scribetw commented on zul/src/archive/web/js/zul/sel/ItemWidget.js
> +			var headerWgt = zk.Widget.$(box._headercm),
Move Listitem._updHeaderCM to here

2021-04-22 01:42 UTC, scribetw approved these changes

2021-04-22 01:42 UTC, plijyfes approved these changes

2021-04-22 01:42 UTC, merged