ZK-4852: JS errors swallowed during widget class initialization
zkoss/zk pull request #2503
Opened 2021-04-22 08:18 UTC by DevChu

2021-04-22 09:49 UTC, scribetw requested changes

2021-04-22 09:49 UTC, scribetw commented on zk/src/org/zkoss/zk/ui/http/WpdExtendlet.java
> +			write(out, "\n}catch(error){console.error(error);}finally{zk.setLoaded(zk._p.n);}");
find outer try and use `zk.debugLog(ex.message || ex);`

2021-04-26 07:20 UTC, plijyfes approved these changes

2021-04-26 09:05 UTC, scribetw approved these changes

2021-04-26 09:06 UTC, scribetw commented
@zkadmin rebase

2021-04-26 09:07 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-04-26 09:08 UTC, merged