ZK-4855: some ListProxy methods set _dirty directly instead of callin…
zkoss/zk pull request #2507
Opened 2021-04-23 03:35 UTC by DevChu

…g setDirty, missing updates

2021-04-23 09:37 UTC, scribetw requested changes

2021-04-23 09:37 UTC, scribetw commented on zkbind/src/org/zkoss/bind/proxy/FormProxyHandler.java
> +				String zkFormProxyNotifiedKey = "$$zkFormProxyNotified$$" + data[0];
Attribute name is "$$zkFormProxyNotified$$", use Set<Pair<Object, String>>

2021-04-26 09:08 UTC, DevChu reviewed
write a case for same exec but later change

2021-04-27 09:09 UTC, scribetw requested changes

2021-04-27 09:09 UTC, scribetw commented on zkbind/src/org/zkoss/bind/impl/BinderImpl.java
> +			if (zkProxyNotified != null && zkProxyNotified.size() > 0)
only `zkProxyNotified != null`

2021-04-27 09:09 UTC, scribetw commented on zkbind/src/org/zkoss/bind/proxy/ListProxy.java
> +		E prevElement = ((List<E>) getCache()).set(index, element);
createProxyObject(element)

2021-04-27 09:22 UTC, scribetw requested changes

2021-04-27 09:22 UTC, scribetw commented on zkbind/src/org/zkoss/bind/proxy/ListProxy.java
> -		_dirty = true;
check addAll

2021-04-27 09:33 UTC, plijyfes approved these changes

2021-04-27 09:34 UTC, scribetw approved these changes

2021-04-27 09:34 UTC, merged