refine mvvm client binding test case
zkoss/zk pull request #2546
Opened 2021-05-20 09:29 UTC by DevChu

2021-05-20 09:49 UTC, scribetw commented on zktest/src/archive/bind/databinding/clientbinding/ClientBinding.zul
> +		<button id="clientOnClickBtn" label="Client namespace" w:onClick='@command("hello", {data: zk.Widget.$(this).getLabel()})'/>
Missing zhtml component test

2021-05-20 09:50 UTC, scribetw requested changes
Missing zhtml component test

2021-05-21 08:07 UTC, scribetw approved these changes

2021-05-21 08:39 UTC, plijyfes approved these changes

2021-05-21 08:42 UTC, merged