ZK-4866: Allow focussing arbitrary components/elements
zkoss/zk pull request #2561
Opened 2021-05-28 04:08 UTC by DevChu

2021-05-28 09:48 UTC, DevChu commented on zktest/src/archive/test2/F96-ZK-4866.zul
> +			Clients.evalJavaScript("zk.$('$title').focus()");
add java api

2021-05-28 09:50 UTC, DevChu commented on zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4866Test.java
> +		for (int num = 2; num < 5; num++) {
<= 4

2021-05-28 10:10 UTC, plijyfes approved these changes

2021-05-28 10:40 UTC, scribetw requested changes

2021-05-28 10:40 UTC, scribetw commented on zk/src/archive/web/js/zk/dom.ts
> +		if (!jq.nodeName(n, 'button', 'input', 'textarea', 'a', 'select', 'iframe') && n.getAttribute('tabindex') === undefined)
n.getAttribute('tabindex') could be null

2021-05-31 03:20 UTC, scribetw approved these changes

2021-05-31 03:20 UTC, merged