ZK-4922: zEmbedded upload fails
zkoss/zk pull request #2595
Opened 2021-06-18 03:31 UTC by DevChu

ZK-4923: zEmbedded download fails

2021-06-18 09:13 UTC, DevChu commented on zk/src/archive/web/js/zk/au.ts
> +				url = updateURI.substr(0, updateURI.indexOf(dt.contextURI)) + url;
substring

2021-06-18 09:20 UTC, DevChu commented on zk/src/archive/web/js/zk/au.ts
> +				url = updateURI.substr(0, updateURI.indexOf(dt.contextURI)) + url;
use general function (look into zk host url)

2021-06-18 10:27 UTC, scribetw requested changes
refine needed

2021-06-22 09:10 UTC, DevChu commented on zktest/src/archive/test2/B96-ZK-4923-1.zul
> +	<image src="/img/sun.jpg"/>
+ ~./
+ ../

2021-06-22 09:11 UTC, DevChu commented on zktest/src/archive/test2/B96-ZK-4923-1.zul
> +	<image src="/img/sun.jpg"/>
remove other comps

2021-06-22 09:42 UTC, scribetw requested changes
test case should be refined

2021-06-23 02:30 UTC, plijyfes approved these changes

2021-06-23 09:45 UTC, DevChu commented on zktest/src/archive/test2/B96-ZK-4923-1.zul
> +	<image src="./img/corner.gif"/>
src="xx.png" (current path)

2021-06-23 09:49 UTC, DevChu commented on zktest/src/archive/test2/B96-ZK-4923-1.zul
> +	<image src="./img/corner.gif"/>
reverse condition, if no absolute -> need add prefix

2021-06-24 09:21 UTC, scribetw approved these changes

2021-06-24 09:21 UTC, scribetw commented
@zkadmin rebase

2021-06-24 09:23 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-06-24 09:32 UTC, merged