ZK-4920: listbox (autopaging) listitem height incorrect between icebl…
zkoss/zk pull request #2598
Opened 2021-06-18 08:30 UTC by plijyfes

…ue/iceblue_c

2021-06-18 10:02 UTC, plijyfes commented on zktest/src/archive/test2/config.properties
> +##manually##B96-ZK-4920.zul=A,E,MeshWidget,autopaging,paging,CSS,Style,Themes
add ZATS

2021-06-18 10:27 UTC, scribetw requested changes
refine needed

2021-06-21 08:40 UTC, scribetw approved these changes

2021-06-21 08:50 UTC, DevChu approved these changes

2021-06-21 09:10 UTC, scribetw commented
@zkadmin rebase

2021-06-21 09:13 UTC, merged

2021-06-21 09:13 UTC, zkadmin commented
I just pushed up the changes and merged, enjoy!