ZK-4934: ListModelList (Map/Set/Array) supports Form binding
zkoss/zk pull request #2599
Opened 2021-06-18 08:58 UTC by DevChu

2021-06-18 09:26 UTC, DevChu commented on zkbind/src/org/zkoss/bind/proxy/ProxyHelper.java
>  		if (origin instanceof List) {
flat

2021-06-18 09:43 UTC, DevChu commented on zkbind/src/org/zkoss/bind/proxy/ListModelArrayProxy.java
> +/** ListModelArrayProxy.java.
try ListModelProxy

2021-06-18 10:28 UTC, scribetw requested changes
refine needed

2021-06-23 10:18 UTC, plijyfes approved these changes

2021-06-23 10:30 UTC, scribetw approved these changes

2021-06-23 10:30 UTC, merged