ZK-4914: Add toggleable debug / error trace for Clients EvalJavascript
zkoss/zk pull request #2610
Opened 2021-07-02 01:18 UTC by DevChu

2021-07-02 02:03 UTC, DevChu commented on zk/src/archive/web/js/zk/mount.ts
> +	if (zk['scriptErrorHandlerEnabled']) {
d.ts

2021-07-02 02:11 UTC, DevChu commented on zk/src/archive/web/js/zk/au.ts
> +		} finally {
why no catch 
https://bugs.jquery.com/ticket/8784

2021-07-02 02:12 UTC, DevChu commented on zk/src/org/zkoss/zk/ui/script/DefaultScriptErrorListener.java
> +		final Map<String, String> data = (Map<String, String>) event.getData();
ScriptErrorEvent

2021-07-02 02:19 UTC, DevChu commented on zk/src/archive/web/js/zk/au.ts
> +			if (scriptErrorHandler)
why if aync

2021-07-05 02:08 UTC, DevChu commented on zk/src/archive/web/js/zk/au.ts
> +		let scriptErrorHandler = zk.scriptErrorHandler;
check stack trace (try async) -> from Clients.evalJavascript

2021-07-05 02:09 UTC, DevChu commented on zk/src/archive/web/js/zk/au.ts
> +		let scriptErrorHandler = zk.scriptErrorHandler;
get all error -> separate global or ZK

2021-07-06 09:09 UTC, DevChu commented on zk/src/archive/web/js/zk/mount.ts
> +				checkFunctionList = (zk.ff || zk.safari) ? ['DOMEval@', 'globalEval@', 'script@', 'doProcess@', 'doCmdsNow@']
remove "@" and " ("

2021-07-06 09:12 UTC, DevChu commented on zk/src/org/zkoss/zk/ui/event/ScriptErrorEvent.java
> +		super(name, new AbstractComponent()); //put dummy target
change to static?

2021-07-06 09:21 UTC, DevChu commented on zktest/src/archive/test2/F96-ZK-4914.zul
> +		<button id="btn" onClick='Clients.evalJavaScript("zk.log(\"log\");")'>Click and see zk log </button>
add two setTimeout case

2021-07-06 09:26 UTC, DevChu commented on zk/src/archive/web/js/zk/au.ts
> +			zk.scriptErrorHandlerRegistered = true;
off -> one (don't use flag)

2021-07-06 09:27 UTC, DevChu commented on @types/zk/zk.d.ts
> +        scriptErrorHandlerRegistered?: boolean;
remove

2021-07-07 02:22 UTC, scribetw requested changes
Is dummy component static?

2021-07-07 09:02 UTC, scribetw approved these changes

2021-07-07 09:27 UTC, merged