ZK-4543: Calendar should respect the constraint while Month changing
zkoss/zk pull request #2612
Opened 2021-07-02 04:22 UTC by b952426

ZK-4543: Calendar should respect the constraint while Month changing

2021-07-06 09:33 UTC, b952426 commented on zul/src/archive/web/js/zul/db/Calendar.js
> +		if(this._selectedValue == null) this._selectedValue = today;
if ()

2021-07-06 09:39 UTC, b952426 commented on zul/src/archive/web/js/zul/db/Calendar.js
> +			if (!this._isSelectDisabled) {
var _isSelectDisabled? or use Renderer.disabled()

2021-07-06 09:41 UTC, b952426 commented on zul/src/archive/web/js/zul/db/Calendar.js
> +									selCell = '';
selCell = null;

2021-07-06 09:43 UTC, b952426 commented on zul/src/archive/web/js/zul/db/Calendar.js
var disabledCell = Renderer.disabled(this, y, m + monofs, v, today);

2021-07-07 02:28 UTC, scribetw requested changes

2021-07-07 02:28 UTC, scribetw commented on zul/src/archive/web/js/zul/db/Calendar.js
> +		var selDate = this.getTime();
unused var

2021-07-07 02:28 UTC, scribetw commented on zul/src/archive/web/js/zul/db/Calendar.js
> +	_getSelectedValue: function () {
remove this unused method

2021-07-07 02:48 UTC, plijyfes approved these changes

2021-07-07 02:49 UTC, scribetw approved these changes

2021-07-07 02:49 UTC, scribetw commented
@zkadmin rebase

2021-07-07 02:50 UTC, DevChu approved these changes

2021-07-07 02:51 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-07-07 03:03 UTC, merged