ZK-4948: URL forwarding/redirection in zEmbedded
zkoss/zk pull request #2626
Opened 2021-07-08 06:48 UTC by DevChu

2021-07-08 07:51 UTC, scribetw requested changes

2021-07-08 07:51 UTC, scribetw commented on zktest/src/archive/test2/B96-ZK-4948-test.html
> +				zEmbedded.load('aaa', '/4948-embedded/B96-ZK-4948.zul', 'http://localhost:8080');
Place it in zk.xml is better

2021-07-08 09:18 UTC, scribetw approved these changes

2021-07-09 01:39 UTC, plijyfes approved these changes

2021-07-09 01:40 UTC, plijyfes commented
@zkadmin rebase

2021-07-09 01:42 UTC, zkadmin commented
I just pushed up the changes, enjoy!

2021-07-09 01:52 UTC, merged