ZK-4938: Textbox can fire an onChanging event when users enter a pred…
zkoss/zk pull request #2636
Opened 2021-07-13 02:39 UTC by plijyfes

…ictive text on iPhone

2021-07-13 03:33 UTC, scribetw approved these changes

2021-07-14 02:32 UTC, DevChu approved these changes

2021-07-14 02:45 UTC, scribetw requested changes

2021-07-14 02:45 UTC, scribetw commented on zul/src/archive/web/js/zul/inp/InputWidget.js
> +		this._updateValue();
See if pasteEvent needs to be stopped

2021-07-14 03:47 UTC, scribetw approved these changes

2021-07-14 03:50 UTC, DevChu approved these changes

2021-07-14 03:52 UTC, merged