refine ZK-4748: bandpopup close while open the treeitem in No-A11y
zkoss/zk pull request #2661
Opened 2021-07-27 09:21 UTC by b952426

refine ZK-4748: bandpopup close while open the treeitem in No-A11y

2021-07-27 10:02 UTC, scribetw requested changes
Consider Leon's advice

2021-07-27 10:03 UTC, plijyfes approved these changes

2021-07-27 10:39 UTC, scribetw approved these changes

2021-07-27 10:50 UTC, scribetw requested changes

2021-07-27 10:50 UTC, scribetw commented on zul/src/archive/web/js/zul/inp/Bandpopup.js
> +		self._shallClosePopup = e.relatedTarget != pp;
consider the case if pp = null

2021-07-28 03:02 UTC, scribetw approved these changes

2021-07-28 03:02 UTC, merged